# Somewhat copied from: https://github.com/p3t33/nixos_flake/blob/master/modules/home-manager/tmux.nix
{
  pkgs,
  config,
  ...
}: let
  resurrectDirPath = "~/.config/tmux/resurrect";
in {
  home-manager.users.${config.userDefinedGlobalVariables.mainUsername}.programs.tmux = {
    enable = true;
    terminal = "tmux-256color";
    historyLimit = 100000;
    keyMode = "vi";
    escapeTime = 0;
    plugins = with pkgs.tmuxPlugins; [
      sensible
      tmux-fzf
      {
        plugin = resurrect;
        extraConfig = ''
          # I have tested this strategy to work with neovim but it is not enough to have
          # Session.vim at the root of the path from which the plugin is going to do the restore
          # it is important that for neovim to be saved to be restored from the path where Session.vim
          # exist for this flow to kick in. Which means that even if tmux-resurrect saved the path with
          # Session.vim in it but vim was not open at the time of the save of the sessions then when
          # tmux-resurrect restore the window with the path with Session.vim nothing will happen.

          # Furthermore I currently using vim-startify which among other things is able to restore
          # from Session.vim if neovim is opened from the path where Session.vim exist. So in a
          # sense I don't really need tmux resurrect to restore the session as this already
          # taken care of and this functionality becomes redundant. But as I am not sure if I keep
          # using vim-startify or its auto restore feature and it do not conflict in any way that
          # I know of with set -g @resurrect-strategy-* I decided to keep it enabled for the time being.
          set -g @resurrect-strategy-nvim 'session'
          set -g @resurrect-strategy-vim 'session'

          set -g @resurrect-capture-pane-contents 'on'

          # This two lines are specific to NixOS and they are intended
          # to edit the tmux_resurrect_* files that are created when tmux
          # session is saved using the tmux-resurrect plugin. Without going
          # into too much details the strings that are saved for some applications
          # such as nvim, vim, man... when using NixOS, appimage, asdf-vm into the
          # tmux_resurrect_* files can't be parsed and restored. This addition
          # makes sure to fix the tmux_resurrect_* files so they can be parsed by
          # the tmux-resurrect plugin and successfully restored.
          set -g @resurrect-dir ${resurrectDirPath}
          set -g @resurrect-hook-post-save-all 'sed -i -E "s|(pane.*nvim\s*:)[^;]+;.*\s([^ ]+)$|\1nvim \2|" ${resurrectDirPath}/last'

          set -g @resurrect-processes '"~hx"'
          set -g @resurrect-save 'C-s'
          set -g @resurrect-restore 'C-r'
        '';
      }

      {
        plugin = continuum;
        extraConfig = ''
          # a few words about @continuum-boot and @continuum-systemd-start-cmd that
          # are not used as part of the extraConfig for the continuum plugin.
          #
          # @continuum-boot - when set will generate a user level systemd unit file
          # which it will save to $HOME/.config/systemd/user/tmux.service and enable
          # it.
          #
          # @continuum-systemd-start-cmd - The command used to start the tmux server
          # is determined via this configuration, and this command is set in the
          # context of the systemd unit file that is generated by setting @continuum-boot
          # when this option is not set the default will be "tmux new-session -d"
          # This setting provides a more fine grain option over the creation of the
          # systemd unit.
          #
          # Having said all that, it is important to understand that systemd units
          # are defined as .nix settings and then created when NixOS is built and
          # nothing is generated "willy-nilly" by applications.
          # So this aspect of the plugin is already taken care of by me in a separate
          # systemd unit that is responsible to start tmux when system starts.
          #
          # set -g @continuum-save-interval is written into the status-right which
          # means that any other plugin that writes into status-right needs to be
          # loaded first or the autosave functionality will not work.
          #
          # More then that it looks like the autosave feature(set -g @continuum-save-interval)
          # only works if you are attached to tmux, for some reason it does not work
          # in detached mode. Maybe if no one is attached then there is nothing
          # changing and so nothing to save.
          #
          # If autosave option interval is not set there is a default of 15 minutes
          # and it worked for me when tested.
          set -g @continuum-restore 'on'
          set -g @continuum-save-interval '10'
        '';
      }
    ];
    extraConfig = ''
      # This command is executed to address an edge case where after a fresh install of the OS no resurrect
      # directory exist which means that the continuum plugin will not work. And so without user
      # manually saving the first session(prfix + Ctrl+s) no resurrect-continuum will occur.
      #
      # And in case user does not remember to save his work for the first time and tmux daemon gets
      # restarted next time user will try to attach, there will be no state to attach to and user will
      # be scratching his head as to why.
      #
      # Saving right after fresh install on first boot of the tmux daemon with no sessions will create an
      # empty "last" session file which might cause all kind of issues if tmux gets restarted before
      # the user had the chance to work in it and let continuum plugin to take over and create
      # at least one valid "snapshot" from which tmux will be able to resurrect. This is why an initial
      # session named init-resurrect is created for resurrect plugin to create a valid "last" file for
      # continuum plugin to work off of.
      run-shell "if [ ! -d ${resurrectDirPath} ]; then tmux new-session -d -s init-resurrect; ${pkgs.tmuxPlugins.resurrect}/share/tmux-plugins/resurrect/scripts/save.sh; fi"

      set -g mouse on
      set -g allow-passthrough on
      set -g detach-on-destroy off
      set -ga update-environment TERM
      set -ga update-environment TERM_PROGRAM
      set -ga terminal-overrides ",*256col*:Tc"
      set -g default-terminal "tmux-256color"
      set-option -g default-shell /run/current-system/sw/bin/bash
      set-option -g default-command /run/current-system/sw/bin/fish

      # Shortcuts

      bind -n M-k run-shell "~/.config/nixos/scripts/tmux/shortcuts/focus_right.sh"
      bind -n M-j run-shell "~/.config/nixos/scripts/tmux/shortcuts/focus_left.sh"
      bind -n M-t run-shell "~/.config/nixos/scripts/tmux/shortcuts/new_window_left.sh"
      bind -n M-n run-shell "~/.config/nixos/scripts/tmux/shortcuts/new_panel.sh"
      bind -n M-m run-shell "~/.config/nixos/scripts/tmux/shortcuts/new_panel_v.sh"
      bind -n M-w kill-pane

      # Git scripts

      bind -n M-p run-shell "tmux neww ~/.config/nixos/scripts/tmux/command_palette/command_palette.sh"

      # Session manager

       bind -n M-o run-shell "~/.config/nixos/scripts/tmux/sessionizer/sessionizer.sh"
       bind -n M-Tab switch-client -l

      # Copy mode

       bind -n M-Escape copy-mode
       bind -T copy-mode-vi V send-keys -X select-line
       bind -T copy-mode-vi M-v send-keys -X rectangle-toggle
       bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -selection clipboard"
       bind -T copy-mode-vi M-v send-keys -X rectangle-toggle

      # To do: Move these to river. When I update to a nixos version that supports more than 10 tags

       bind -n M-g run-shell "~/.config/nixos/scripts/tmux/shortcuts/toggle_git.sh"
       bind -n M-d run-shell "~/.config/nixos/scripts/tmux/shortcuts/toggle_docker.sh"

       # Status bar style

       set -g window-status-format "   #W"
       set -g window-status-current-format "   #W"
       set -g status-position top
       set -g status-left ""
       # set -g status-justify absolute-centre
       # set -g status-justify left
       set -g status-justify right
       # Dark grey: colour234 (#1c1c1c)
       # Medium grey: colour236 (#303030)
       # Medium grey blueish: (#222828)
       # Light grey: colour248 (#a8a8a8)
       # VeryLight grey: colour254 (#e4e4e4)
       # Green: colour46 (#00ff00)
       # Magenta: colour201 (#ff00ff)
       # set -g status-right              "#[bg=#222828,fg=colour201] #S  "
       set -g status-right              "              #[bg=#222828,fg=colour201] #S   "
       set -g status-style                "bg=#222828"
       set -g window-status-style         "bg=#222828,fg=colour248"
       set -g window-status-current-style "bg=#222828,fg=colour46"
       set -g message-command-style       "bg=colour46,fg=#222828, bold"
       set -g message-style               "bg=colour46,fg=#222828, bold"
       set -g pane-border-style           "fg=colour236"
       set -g pane-active-border-style    "fg=colour236"
    '';
  };
}
